apiVersion: v1
kind: PersistentVolume
metadata:
  name: dind-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./utils/daemon.json"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi