FROM jelastic/maven:3.9.5-openjdk-21

SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app
ONBUILD WORKDIR /appi
RUN mvn dependency:resolve -f ./pom.xml
RUN mvn package -f ./pom.xml
ONBUILD CMD ["java", "-jar", "target/app.jar"]
