FROM jelastic/maven:3.9.5-openjdk-21

SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app
ONBUILD WORKDIR /app
ONBUILD RUN mvn dependency:resolve -f ./app/pom.xml
ONBUILD RUN mvn package -f ./app/pom.xml
ONBUILD CMD ["java", "-jar", "target/app.jar"]
