#!/bin/bash

user=$(whoami)
if [ $user != "root" ]; then
    echo "You must be root to run this script"
    exit 1
fi

cd /home/$(whoami)/
helm install whanos helm/Whanos -f whanos.yaml > log.txt 2>&1

