FROM gcc:latest as builder

RUN apt-get update && apt-get install -y cmake
SHELL ["/bin/bash", "-c"]
COPY ./app /app
WORKDIR /app
RUN cmake -S . -B build && cmake --build build

FROM alpine:latest

RUN apk add --no-cache libstdc++ libgcc bash
SHELL ["/bin/bash", "-c"]
COPY --from=builder /app/build/ /app
WORKDIR /app
CMD ["./compiled-app"]
